#include "TH1.h"
#include "TFile.h"
#include "TChain.h"
#include "TGraph.h"
#include "TCanvas.h"
#include "TLegend.h"
#include "TStyle.h"
#include "TROOT.h"


void mpcFig()
{
	//these numbers gathered from meanPeakCorr macro on real data
	double realDist[] = {0.73025, 0.7874, 0.9398, 1.1303, 1.7653};
	double realMPC[] = {0.0508134, 0.0494977, 0.0505951, 0.0504085, 0.0501416};
	double realRMS[] = {0.0119522, 0.0114016, 0.0123086, 0.0110692, 0.0109392};

	//these files generated by toyModelImproved
	const char * f[] = {"150_cm", "270_cm", "0_cm", "1_cm", "5_cm",
		"10_cm", "15_cm", "20_cm", "25_cm", "35_cm", "40_cm",
		"45_cm", "50_cm", "55_cm", "65_cm", "space0", "space1",
		"space4", "space2", "space3"};

	double spaces[] = {1.5, 2.7, 0.001, .01, .05, .1, .15, .2, .25, .35, .4, .45, .5, .55, .65, .73025, .7874, .9398, 1.1303, 1.7653};

	TString anttype = "vpol";
	TString geomtype= "_shell_";
	TString dirname = "simFiles/";
	TString simname = anttype + geomtype;
	TString simend  = "CorrHistosTEST.root";

	int simPts = 20;
	int realPts = 5;

	TGraphErrors * gSim = new TGraphErrors(simPts);
	TGraphErrors * gReal = new TGraphErrors(realPts);

	for (int i = 0; i < simPts; i++)
	{
		TString curr = f[i];
		TString histoFile = dirname + anttype + "/"+anttype+geomtype + curr + simend;
		TFile f(histoFile.Data());
		TH1F * h = (TH1F*) f.Get("meanPeakCorr");

		gSim->SetPoint(i, spaces[i], h->GetMean());
		gSim->SetPointError(i, 0, h->GetRMS());
	}

	for (int i = 0; i < realPts; i++)
	{
		gReal->SetPoint(i, realDist[i], realMPC[i]);
		gReal->SetPointError(i, 0, realRMS[i]);
	}

	TCanvas * c1 = new TCanvas;
	gStyle->SetLegendBorderSize(0);
	gStyle->SetLegendFillColor(10);
	gStyle->SetFillColor(10);
	//gStyle->SetLegendFont(102);
	//gStyle->SetTitleFont(102);
	//gStyle->SetLabelFont(102);
	gPad->SetTicks(1,1);

	c1->SetLogx();
	//gSim->GetYaxis()->SetTitleFont(102);
	//gSim->GetXaxis()->SetTitleFont(102);
	gSim->SetLineWidth(1);
	gSim->SetLineColor(kRed);
	gSim->SetMarkerStyle(kFullCircle);
	gSim->SetMarkerColor(kRed);
	gSim->SetMarkerSize(.75);

	gReal->SetLineWidth(1);
	gReal->SetLineColor(kBlue);
	gReal->SetMarkerStyle(kFullSquare);
	gReal->SetMarkerColor(kBlue);
	gReal->SetMarkerSize(.7);

	gSim->SetTitle(simname.Data());
	gSim->GetXaxis()->SetLimits(.0007,4);
	gSim->GetYaxis()->SetRangeUser(0,1);
	gSim->GetXaxis()->SetTitle("Distance Between Antennas (m)");
	gSim->GetYaxis()->SetTitle("Mean Peak Correlation Coefficient");
	gSim->GetXaxis()->CenterTitle();
	gSim->GetYaxis()->CenterTitle();
	gSim->Draw("ap");
	gReal->Draw("p");

	TLegend * leg = new TLegend(.67, .67, .87, .87);
	leg->AddEntry(gSim, "Simulation", "p");
	leg->AddEntry(gReal, "Data", "p");
	leg->Draw();
}




